name = "FastPrimeSieve"
uuid = "715f0e73-5d43-4f21-b094-9019e1b56aa3"
authors = ["Harmen Stoppels <me@harmenstoppels.nl>"]
version = "0.1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
julia = "1.3"